<!-- Blog Sidebar -->
<aside class="blog-sidebar">

    <!-- CTA Box -->
    <div class="sidebar-widget sidebar-cta">
        <div class="cta-box">
            <div class="cta-box-icon">🎯</div>
            <h3 class="cta-box-title">Ready to Challenge Your Brain?</h3>
            <p class="cta-box-text">Start playing Sudoku now and improve your logical thinking!</p>
            <a href="<?php echo home_url('/sudoku'); ?>" class="btn btn-sidebar-cta">Play Now</a>
        </div>
    </div>

    <!-- Table of Contents -->
    <?php if (is_single()): ?>
    <div class="sidebar-widget sidebar-toc">
        <h3 class="sidebar-widget-title">Table of Contents</h3>
        <div class="toc-content" id="toc-content">
            <!-- ToC will be generated by JavaScript -->
        </div>
    </div>
    <?php endif; ?>

    <!-- Recent Posts -->
    <div class="sidebar-widget sidebar-recent">
        <h3 class="sidebar-widget-title">Recent Posts</h3>
        <?php
        $recent_posts = new WP_Query(array(
            'posts_per_page' => 5,
            'post_status' => 'publish',
            'post__not_in' => array(get_the_ID())
        ));

        if ($recent_posts->have_posts()) :
        ?>
        <ul class="recent-posts-list">
            <?php while ($recent_posts->have_posts()) : $recent_posts->the_post(); ?>
            <li class="recent-post-item">
                <?php if (has_post_thumbnail()): ?>
                <a href="<?php the_permalink(); ?>" class="recent-post-thumb">
                    <?php the_post_thumbnail('thumbnail'); ?>
                </a>
                <?php endif; ?>
                <div class="recent-post-content">
                    <a href="<?php the_permalink(); ?>" class="recent-post-title">
                        <?php the_title(); ?>
                    </a>
                    <span class="recent-post-date"><?php echo get_the_date(); ?></span>
                </div>
            </li>
            <?php endwhile; wp_reset_postdata(); ?>
        </ul>
        <?php endif; ?>
    </div>

    <!-- Suggested Games -->
    <div class="sidebar-widget sidebar-games">
        <h3 class="sidebar-widget-title">Try Our Games</h3>
        <div class="suggested-games">
            <a href="<?php echo home_url('/sudoku/easy'); ?>" class="game-card">
                <span class="game-icon">🎲</span>
                <div class="game-info">
                    <h4>Easy Sudoku</h4>
                    <p>Perfect for beginners</p>
                </div>
            </a>
            <a href="<?php echo home_url('/sudoku/medium'); ?>" class="game-card">
                <span class="game-icon">🎯</span>
                <div class="game-info">
                    <h4>Medium Sudoku</h4>
                    <p>Balanced challenge</p>
                </div>
            </a>
            <a href="<?php echo home_url('/sudoku/expert'); ?>" class="game-card">
                <span class="game-icon">🔥</span>
                <div class="game-info">
                    <h4>Expert Sudoku</h4>
                    <p>Ultimate challenge</p>
                </div>
            </a>
        </div>
    </div>

    <!-- Final CTA -->
    <div class="sidebar-widget sidebar-cta-bottom">
        <div class="cta-box cta-box-gradient">
            <h3>Join Our Community</h3>
            <p>Get weekly puzzles and tips!</p>
            <a href="#newsletter" class="btn btn-white">Subscribe</a>
        </div>
    </div>

</aside>
