<!-- Blog Sidebar -->
<aside class="blog-sidebar">

    <!-- Table of Contents -->
    <?php if (is_single()): ?>
    <div class="sidebar-widget sidebar-toc">
        <h3 class="sidebar-widget-title">Table of Contents</h3>
        <div class="toc-content" id="toc-content">
            <!-- ToC will be generated by JavaScript -->
        </div>
    </div>
    <?php endif; ?>

    <!-- Recent Posts -->
    <div class="sidebar-widget sidebar-recent">
        <h3 class="sidebar-widget-title">Recent Posts</h3>
        <?php
        $recent_posts = new WP_Query(array(
            'posts_per_page' => 5,
            'post_status' => 'publish',
            'post__not_in' => array(get_the_ID())
        ));

        if ($recent_posts->have_posts()) :
        ?>
        <ul class="recent-posts-list">
            <?php while ($recent_posts->have_posts()) : $recent_posts->the_post(); ?>
            <li class="recent-post-item">
                <?php if (has_post_thumbnail()): ?>
                <a href="<?php the_permalink(); ?>" class="recent-post-thumb">
                    <?php the_post_thumbnail('thumbnail'); ?>
                </a>
                <?php endif; ?>
                <div class="recent-post-content">
                    <a href="<?php the_permalink(); ?>" class="recent-post-title">
                        <?php the_title(); ?>
                    </a>
                    <span class="recent-post-date"><?php echo get_the_date(); ?></span>
                </div>
            </li>
            <?php endwhile; wp_reset_postdata(); ?>
        </ul>
        <?php endif; ?>
    </div>

    <!-- Final CTA -->
    <div class="sidebar-widget sidebar-cta-bottom">
        <div class="cta-box cta-box-gradient">
            <h3>Join Our Community</h3>
            <p>Get weekly puzzles and tips!</p>
            <a href="#newsletter" class="btn btn-white">Subscribe</a>
        </div>
    </div>

</aside>
